# -*- coding: utf-8 -*-
import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('mandarin.jpg')
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_hsv = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2HSV)
image_lab = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2LAB)

lower_orange_hsv = np.array([5, 50, 50])
upper_orange_hsv = np.array([20, 255, 255])
mask_hsv = cv2.inRange(image_hsv, lower_orange_hsv, upper_orange_hsv)
result_hsv = cv2.bitwise_and(image_rgb, image_rgb, mask=mask_hsv)

lower_orange_lab = np.array([0, 100, 100])
upper_orange_lab = np.array([255, 255, 255])
mask_lab = cv2.inRange(image_lab, lower_orange_lab, upper_orange_lab)
result_lab = cv2.bitwise_and(image_rgb, image_rgb, mask=mask_lab)

plt.figure(figsize=(15, 5))
plt.subplot(1, 4, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis('off')
plt.subplot(1, 4, 2)
plt.imshow(image_hsv)
plt.title("HSV Color Space")
plt.axis('off')
plt.subplot(1, 4, 3)
plt.imshow(result_hsv)
plt.title("HSV Segmentation Result")
plt.axis('off')
plt.subplot(1, 4, 4)
plt.imshow(result_lab)
plt.title("LAB Segmentation Result")
plt.axis('off')
plt.tight_layout()
plt.savefig('lab5_color_segmentation.png', dpi=150)
plt.show()

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(mask_hsv, cmap='gray')
plt.title("HSV Mask")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(mask_lab, cmap='gray')
plt.title("LAB Mask")
plt.axis('off')
plt.tight_layout()
plt.savefig('lab5_masks.png', dpi=150)
plt.show()

h_channel = image_hsv[:, :, 0]
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.hist(h_channel.flatten(), bins=180, range=[0, 180], color='orange', alpha=0.7)
plt.axvline(5, color='r', linestyle='--', label='Lower (5)')
plt.axvline(20, color='b', linestyle='--', label='Upper (20)')
plt.title('Hue Channel Histogram (HSV)')
plt.xlabel('Hue')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True, alpha=0.3)

a_channel = image_lab[:, :, 1]
plt.subplot(1, 2, 2)
plt.hist(a_channel.flatten(), bins=256, range=[0, 255], color='red', alpha=0.7)
plt.axvline(100, color='r', linestyle='--', label='Lower (100)')
plt.title('A Channel Histogram (LAB)')
plt.xlabel('A channel (green-red)')
plt.ylabel('Pixel Count')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('lab5_histograms.png', dpi=150)
plt.show()

print("Lab 5 completed!")
print(f"Image shape: {image_rgb.shape}")
print(f"HSV pixels: {np.sum(mask_hsv > 0)}")
print(f"LAB pixels: {np.sum(mask_lab > 0)}")
